### ISSUE TITLE
Line 37 of ODD file

### ISSUE THREAD

**Issue by bryanwinston-ddhi** [agile-humanities/ddhi-oht-schema#2]
Are you referring to all users as text encoders? We define our potential users as archivists, researchers, students, and community organizations.

**Comment by cwulfman** [comment]
No.  The section is entitled "How to use these guidelines", and it suggests who should read which sections.  The first is high-level, for general readers and others not interested in encoding.  The second section is intended for use by encoders and programmers -- it is technical information that is unlikely to be of interest to those who are not marking up texts or writing programs that need to know things about the schema.

Maybe change the sentence to 
>The second section is intended for use by persons marking up interviews using the DDHI schema and by developers writing software to process DDHI-encoded interview transcriptions.

**Comment by bryanwinston-ddhi** [comment]
Changed the sentence as recommended
